serverRules = [
"Bienvenue sur le Gens Bons Survival Multi Player, ou GBSMP !",
"Les règles de bienséances habituelles sont de mise :",
"- Les comportements déplacés et anti-jeu ne sont pas tolérés",
"- Le grief des espaces privés et publics n'est pas toléré",
"- Le respect des gentlemen rules est fortement recommandé",
"- Ne construis pas ton habitation sur l'île de départ, elle est réservée pour faire une ville commerciale",
"- Un paquet de crafts customs sont ajoutés, donc n'hésite pas à regarder la recette d'un objet même si tu le connais ou si il n'est pas fabriquable",
"- Amuse-toi, pranke tes amis si tu le veux, mais jamais dans un esprit de destruction",
"",
"Tu devrais VRAIMENT lire les nombreux tips disponibles ici : https://github.com/Captn138/gbsmp/blob/main/TIPS.md",
"N'hésite pas à jeter un oeil aux mods du pack, la liste est disponible ici : https://github.com/Captn138/gbsmp/blob/main/README.md",
"",
"En cas de soucis, contacte @captn138 sur Discord"
]
